### ISSUE TITLE
How to get real file extention when using base64 string

### ISSUE THREAD

**Issue by mrmmg** [protonemedia/laravel-mixins#4]
Hi
Thanks for your good package. I'm using the base64 file option but I want to get real file extension. according to docs I make a request and put this code inside it:

```
protected function base64FileKeys(): array
    {
        return [
            'file' => time() . '_Ticket.jpg',    // i want to get file extension dynamically not hard coded!
        ];
    } 
```

it's work and ok but all of my files are not jpg! I want to use pdf or png too. so how can I get real file extension (uploaded file) and put it to mentioned code?

**Comment by pascalbaljet** [comment]
You can't! A base64 encoded file only holds the contents, not the filename. So you need to separately submit the filename (for example, with a hidden input field).
